name: Test

on: 
  workflow_call: # whenever this workflow needs to be called from another

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Test the code"
